const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pantss',
      image: '/images/p2.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality pant',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 55,
      countInStock: 3,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 7,
      description: 'fitness wear',
    },
    {
      name: 'Old Navy Pants',
      slug: 'old-navy-pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 40,
      countInStock: 10,
      brand: 'Old Navy',
      rating: 7.5,
      numReviews: 1,
      description: 'comforatable workwear',
    },
  ],
};

export default data;
